s screenshot video
W screenshot window

. frame-step
, frame-back-step

RIGHT seek 5 exact
LEFT  seek -5 exact

Shift+WHEEL_UP add volume 10
Shift+WHEEL_DOWN add volume -10

F1 script-message osc-visibility never
F2 script-message osc-visibility auto
F3 script-message osc-visibility always